services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: prod-platform-api:local
    ports:
      - "3000:3000"
    environment:
      APP_ENV: docker-compose
      APP_VERSION: 0.1.0

